platform :ios, '13.2'

target 'PetAdoptSampleApp' do
  use_frameworks!
  pod 'AFNetworking', '4.0.1' #Networking
  pod 'YapDatabase', '4.0.1' #Sqlite Database
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
